services:
  app:
    image: app-image
    container_name: parcial1-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/c/Users/Albeto/Parcial1/identifier.sqlite:/app/identifier.sqlite"
    environment:
      - SPRING_PROFILES_ACTIVE=prod